---
version: 2.17.5
slug: marcelo_openthread_border_router
name: OpenThread Border Router (Marcelo's Multi-Instance)
description: OpenThread Border Router add-on with multi-instance support
url: >-
  https://github.com/jmarcelomb/addons/tree/master/openthread_border_router
arch:
  - aarch64
  - amd64
homeassistant: 2025.7.0
gpio: true
hassio_api: true
discovery:
  - otbr
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_uts: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
devices:
  - /dev/net/tun
init: false
options:
  device: null
  baudrate: "460800"
  flow_control: true
  otbr_log_level: notice
  firewall: true
  nat64: false
  beta: false
  thread_interface: wpan1
  disable_border_routing: true
ports:
  8080/tcp: 8090
  8081/tcp: null
ports_description:
  8080/tcp: OpenThread Web UI
  8081/tcp: OpenThread REST API (auto-assigned based on interface number)
schema:
  device: device(subsystem=tty)
  baudrate: list(57600|115200|230400|460800|921600|1000000)
  flow_control: bool
  backbone_interface: str?
  network_device: str?
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  firewall: bool
  nat64: bool
  beta: bool?
  thread_interface: match(^wpan[0-9]$)?
  disable_border_routing: bool
startup: services
